spring:
  rabbitmq:
    addresses: 47.98.116.157
    port: 5672
    username: sxli
    password: 123456
  application:
    name: stream-group-consumer2
  cloud:
    stream:
      bindings:
        inputProduct:
          destination: exchangeProduct
          group: groupProduct
server:
  port: 9086